
CREATE TABLE PROFESORES(
ProfesoresID INT NOT NULL PRIMARY KEY, NOMBRE VARCHAR(255),
APELLIDO1 VARCHAR(255), APELLIDO2 VARCHAR(255),
DNI VARCHAR(255) NOT NULL, DIRECCION VARCHAR(255), 
TITULO VARCHAR(255), GANA INT NOT NULL);

CREATE TABLE CURSO(COD_CURSO INT NOT NULL PRIMARY KEY,
ProfesoresID INT FOREIGN KEY REFERENCES PROFESORES(ProfesoresID), 
NOMBRE_CURSO VARCHAR(255),
DNI_PROFESOR VARCHAR(255), MAXIMO_ALUMNOS INT, 
FECHA_INICIO DATE, FECHA_FIN DATE, 
NUM_HORAS INT);

CREATE TABLE PROFESOR_CURSO(COD_CURSO INT FOREIGN KEY REFERENCES CURSO(COD_CURSO) ON UPDATE CASCADE,
ProfesoresID INT FOREIGN KEY REFERENCES PROFESORES(ProfesoresID) ON UPDATE CASCADE);

CREATE TABLE ALUMNOS(AlumnosID INT IDENTITY(1,1) PRIMARY KEY, NOMBRE VARCHAR(255), 
APELLIDO1 VARCHAR(255), APELLIDO2 VARCHAR(255),
DNI VARCHAR(255), DIRECCION VARCHAR(255),
SEXO VARCHAR(1), FECHA_NACIMIENTO DATE, 
COD_CURSO INT FOREIGN KEY REFERENCES CURSO(COD_CURSO));

CREATE TABLE ALUMNOS_CURSO(COD_CURSO INT FOREIGN KEY REFERENCES CURSO(COD_CURSO) ON UPDATE CASCADE,
AlumnosID INT FOREIGN KEY REFERENCES ALUMNOS(AlumnosID)ON UPDATE CASCADE);



